#!/bin/bash
FILES="mips_testbench/tests/*"

#for F in $FILES
#do
#  bin/parser $F "mips_testbench/binaries/#"
#done
OIFS="$IFS"
IFS=","

for F in $FILES
do
  info_array=()
  test_status="ERROR"
  line=$(head -n 1 $F)

  for word in $line; do
    info_array+=("$word")
  done

  (printf ${info_array[4]})|$1 "mips_testbench/binaries/${info_array[1]}.bin"
  var=$?
  if (($var == ${info_array[3]})); then  #return value
    test_status="PASS"
  else
    test_status="FAIL"
  fi
  printf ${info_array[1]},${info_array[2]},$test_status,${info_array[5]},${info_array[6]}
  echo " "
done

OIFS="$IFS"
IFS="$OIFS"
